
# GET  http://localhost:4004/odata/v4/my/Products



# DELETE http://localhost:4004/odata/v4/my/Products(54) 

# POST http://localhost:4004/odata/v4/my/OrderItems
# Content-Type: application/json
# {
#     "OrderID": 2,
#     "ProductID": 3,
#     "Quantity": 1,
#     "subtotal": 130.00
# }



# POST http://localhost:4004/odata/v4/my/product_create
# Content-Type: application/json

# {
#     "P_NAME": "Jeep",
#     "P_CATEGORY": "Toy",
#     "P_PRICE": 1000,
#     "P_STOCK": 10
# }



# POST http://localhost:4004/odata/v4/my/Customer_create
# Content-Type: application/json

# {
#     "P_NAME": "Ankit Raghuvanshi",
#     "P_EMAIL": "Ankit.Raghuvanshi@gmail.com",
#     "P_PHONE": "9173832332",
#     "P_ADDRESS": "Bhopal",
#     "P_COUNTRY" : "India"
# }

# POST http://localhost:4004/odata/v4/my/Orders
# Content-Type: application/json

# {
#     "OrderID": 10000,
#     "CustomerID": 1,
#     "OrderDate": "2025-03-07T12:00:00Z",
#     "items": [
#         { "OrderItemID": 10000, "ProductID": 20000, "Quantity": 2 },
#         { "OrderItemID": 10001, "ProductID": 21000, "Quantity": 3 }
#     ]
# }



POST http://localhost:4004/odata/v4/my/placeOrder
Content-Type: application/json

{
    "Customers": {
        "Name": "Harsh Agrawal",
        "Phone": "9174901008"
    },
    "OrderDate": "2025-04-07T12:00:00Z",
    "Items": [
        { "ProductID": 1, "Quantity": 2, "Price": 64.29},
        { "ProductID": 2, "Quantity": 1, "Price": 303.32}
    ]
}



# DELETE http://localhost:4004/odata/v4/my/Orders(203)




# POST http://localhost:4004/odata/v4/my/Orders
# Content-Type: application/json

# {
#     "OrderID": 10000,
#     "CustomerID": 1,
#     "OrderDate": "2025-03-07T12:00:00Z"
# }



# POST http://localhost:4004/odata/v4/my/OrderItems
# Content-Type: application/json

# {
#     "OrderItemID": 702,
#     "OrderID": 10000,
#     "ProductID": 2,
#     "Quantity": 2
# }


# GET  http://localhost:4004/odata/v4/my/OrderItems(700)
# GET  http://localhost:4004/odata/v4/my/Orders(10000)